FROM node:alpine

RUN mkdir -p /opt/app
RUN apk add --no-cache libc6-compat
ENV NODE_ENV production
ENV PORT 8080
EXPOSE 8080 4242 4343

WORKDIR /opt/app
RUN npm install && npm cache clean --force
COPY . /opt/app
