version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        - NODE_ENV=development

    # windows needs legacy watch to work
    command: ../node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:4343
    
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development
