version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    
    command: npm start

    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=production
