version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        - NODE_ENV=development

    # windows needs legacy watch to work
    command: npm run windows-dev
    
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development
