version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        - NODE_ENV=development
    
    # use FS events on *nix
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:4343

    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development
